version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  
  pre_build:
    commands:
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://${S3_BUCKET}
      - aws cloudfront create-invalidation --distribution-id ${CF_ID} --paths /index.html