export const answers = [
  [
    'Qual país que fala holandês?',
    'Alemanha',
    'Brasil',
    'Holanda',
    'Espanha',
    3,
  ],
  [
    'Quem pintou a Mona Lisa?',
    'Vincent van Gogh',
    'Pablo Picasso',
    'Leonardo da Vinci',
    'Michelangelo',
    3,
  ],
  [
    'Qual é o maior planeta do nosso sistema solar?',
    'Marte',
    'Terra',
    'Júpiter',
    'Saturno',
    3,
  ],
  [
    'Em que ano a primeira guerra mundial começou?',
    '1914',
    '1918',
    '1939',
    '1945',
    1,
  ],
  ['Qual é a capital do Japão?', 'Pequim', 'Tóquio', 'Seul', 'Hanoi', 2],
  [
    'Quem escreveu "Dom Quixote"?',
    'Miguel de Cervantes',
    'Gabriel García Márquez',
    'Jorge Luis Borges',
    'Pablo Neruda',
    1,
  ],
  ['Qual é a fórmula química da água?', 'H2O', 'CO2', 'NaCl', 'CH4', 1],
  [
    'Qual é o menor país do mundo?',
    'Mônaco',
    'San Marino',
    'Vaticano',
    'Liechtenstein',
    3,
  ],
  [
    'Quem descobriu a América?',
    'Cristóvão Colombo',
    'Vasco da Gama',
    'Ferdinand Magellan',
    'James Cook',
    1,
  ],
  [
    'Qual é o elemento químico com o símbolo Au?',
    'Prata',
    'Ouro',
    'Cobre',
    'Mercúrio',
    2,
  ],
  [
    'Qual é o rio mais longo do mundo?',
    'Nilo',
    'Amazônia',
    'Yangtze',
    'Mississippi',
    1,
  ],
  [
    'Quem escreveu "A Odisséia"?',
    'Homero',
    'Sófocles',
    'Eurípides',
    'Aristóteles',
    1,
  ],
  [
    'Qual é a moeda oficial do Reino Unido?',
    'Euro',
    'Dólar',
    'Libra Esterlina',
    'Franco Suíço',
    3,
  ],
  [
    'Qual é o maior oceano do mundo?',
    'Atlântico',
    'Índico',
    'Ártico',
    'Pacífico',
    4,
  ],
  [
    'Qual é a língua mais falada no mundo?',
    'Inglês',
    'Mandarim',
    'Espanhol',
    'Francês',
    2,
  ],
  [
    'Qual é a montanha mais alta do mundo?',
    'K2',
    'Kangchenjunga',
    'Everest',
    'Lhotse',
    3,
  ],
  [
    'Quem é o autor de "O Senhor dos Anéis"?',
    'J.K. Rowling',
    'George R.R. Martin',
    'J.R.R. Tolkien',
    'C.S. Lewis',
    3,
  ],
  [
    'Qual é o maior país em termos de área?',
    'Canadá',
    'China',
    'Rússia',
    'Estados Unidos',
    3,
  ],
  [
    'Quem foi o primeiro homem a pisar na Lua?',
    'Yuri Gagarin',
    'Neil Armstrong',
    'Buzz Aldrin',
    'Michael Collins',
    2,
  ],
  ['Qual é a capital da França?', 'Berlim', 'Madri', 'Roma', 'Paris', 4],
  ['Qual é a fórmula da glicose?', 'C6H12O6', 'C5H10O5', 'C6H6O6', 'C4H6O4', 1],
  [
    'Quem pintou "A Última Ceia"?',
    'Leonardo da Vinci',
    'Michelangelo',
    'Raphael',
    'Titian',
    1,
  ],
  [
    'Qual é o maior deserto do mundo?',
    'Saara',
    'Gobi',
    'Antártida',
    'Kalahari',
    3,
  ],
  [
    'Qual é o continente mais populoso?',
    'África',
    'América do Norte',
    'Ásia',
    'Oceania',
    3,
  ],
  [
    'Quem foi o presidente dos EUA durante a Segunda Guerra Mundial?',
    'Franklin D. Roosevelt',
    'Harry S. Truman',
    'Dwight D. Eisenhower',
    'John F. Kennedy',
    1,
  ],
  [
    'Qual é a unidade de medida da força no Sistema Internacional?',
    'Newton',
    'Joule',
    'Pascal',
    'Watt',
    1,
  ],
  [
    'Qual é o livro mais vendido de todos os tempos?',
    'O Senhor dos Anéis',
    'Harry Potter e a Pedra Filosofal',
    'A Bíblia',
    'Dom Quixote',
    3,
  ],
  [
    'Qual é o nome do maior vulcão ativo do mundo?',
    'Vulcão Mauna Loa',
    'Vulcão Etna',
    'Vulcão Fuji',
    'Vulcão Vesúvio',
    1,
  ],
  [
    'Quem é o autor de "Cem Anos de Solidão"?',
    'Mario Vargas Llosa',
    'Gabriel García Márquez',
    'Isabel Allende',
    'Jorge Luis Borges',
    2,
  ],
  [
    'Qual é o planeta mais próximo do Sol?',
    'Terra',
    'Marte',
    'Mercúrio',
    'Vênus',
    3,
  ],
  [
    'Qual é a capital da Austrália?',
    'Sydney',
    'Melbourne',
    'Canberra',
    'Brisbane',
    3,
  ],
  [
    'Qual é o maior animal terrestre?',
    'Elefante Africano',
    'Rinoceronte',
    'Hipopótamo',
    'Girafa',
    1,
  ],
  [
    'Quem inventou o telefone?',
    'Alexander Graham Bell',
    'Thomas Edison',
    'Nikola Tesla',
    'Michael Faraday',
    1,
  ],
  [
    'Qual é a principal língua falada no Brasil?',
    'Espanhol',
    'Português',
    'Inglês',
    'Francês',
    2,
  ],
  [
    'Qual é o menor osso do corpo humano?',
    'Esterno',
    'Fêmur',
    'Estribo',
    'Cóccix',
    3,
  ],
  [
    'Quem foi o fundador da Microsoft?',
    'Steve Jobs',
    'Bill Gates',
    'Elon Musk',
    'Mark Zuckerberg',
    2,
  ],
  [
    'Qual é o elemento químico com o símbolo Fe?',
    'Ferro',
    'Flúor',
    'Fósforo',
    'Neônio',
    1,
  ],
  [
    'Qual é a capital do Canadá?',
    'Toronto',
    'Vancouver',
    'Montreal',
    'Ottawa',
    4,
  ],
  [
    'Quem escreveu "O Pequeno Príncipe"?',
    'Antoine de Saint-Exupéry',
    'Jules Verne',
    'Lewis Carroll',
    'Hans Christian Andersen',
    1,
  ],
  [
    'Qual é o maior lago do mundo por volume de água?',
    'Lago Baikal',
    'Lago Superior',
    'Lago Vitória',
    'Lago Titicaca',
    1,
  ],
]

export interface TypeQuestions {
  question: string
  options: Array<string | number>
  answer: string
  hasBeenUsed: boolean
}

export const questionsObj = answers.map((item) => ({
  question: item[0].toString(),
  options: item.slice(1, -1),
  answer: (Number(item[5]) - 1).toString(),
  hasBeenUsed: false,
}))
